//! `ftnl completion --shell <bash|zsh>` — print a static completion script.
//!
//! Generated by the flags-2-env core from `.cli-flags.toml`, so it stays correct
//! as flags change and does no TOML reading or process spawning while the shell
//! is completing.
//!
//! ```sh
//! ftnl completion --shell bash > ~/.local/share/bash-completion/completions/ftnl
//! ftnl completion --shell zsh  > ~/.zfunc/_ftnl
//! ```

use std::path::Path;

use crate::error::CliError;
use crate::flags::CliArgs;

pub fn run(args: &CliArgs, config_path: &Path) -> Result<i32, CliError> {
    let script = crate::help::completion_script(config_path, &args.shell, crate::PROGRAM)?;
    // Deliberately not `emit`: the output is a shell script, so `--json` does
    // not apply and must not wrap it.
    print!("{script}");
    Ok(0)
}
