#!/usr/bin/env bash
# Freeze or thaw the one generated source file owned by `.cli-flags.toml`.
# Git does not persist write bits, so validation reapplies the frozen policy
# after checkout. The marker check fails closed before permissions are changed.
set -euo pipefail

root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
readonly root
readonly generated="$root/src/cli_config.rs"
readonly expected_marker='// Generated by flags2env from .cli-flags.toml. Do not edit.'
readonly operation="${1:---freeze}"

[[ -f "$generated" ]] || {
  echo "missing generated config: src/cli_config.rs" >&2
  exit 1
}

IFS= read -r first_line <"$generated"
[[ "$first_line" == "$expected_marker" ]] || {
  echo "src/cli_config.rs is missing the flags2env generated marker" >&2
  exit 1
}

case "$operation" in
  --freeze)
    chmod a-w "$generated"
    ;;
  --thaw)
    chmod u+w "$generated"
    ;;
  --check) ;;
  *)
    echo "usage: scripts/freeze-generated.sh [--freeze|--thaw|--check]" >&2
    exit 2
    ;;
esac

python3 - "$generated" "$operation" <<'PY'
import pathlib
import stat
import sys

path = pathlib.Path(sys.argv[1])
operation = sys.argv[2]
writable_bits = stat.S_IMODE(path.stat().st_mode) & 0o222

if operation in {"--freeze", "--check"} and writable_bits:
    raise SystemExit(f"{path}: generated config is writable (mode has {writable_bits:#05o})")
if operation == "--thaw" and not (writable_bits & stat.S_IWUSR):
    raise SystemExit(f"{path}: generated config did not become owner-writable")
PY

printf '%s\n' "src/cli_config.rs: ${operation#--}"
