// Generated by flags2env from .cli-flags.toml. Do not edit.

#[allow(non_snake_case)]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CliConfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_APPLICATION_ID: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_ACCEPT: Option<Vec<serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_MAX_FILES: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_MAX_FILE_BYTES: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_EXPIRES_IN_SECONDS: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_FILE: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_MEDIA_TYPE: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_JOB_ID: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_FILE_ID: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_OUT: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_FORCE: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_COMPLETION_SHELL: Option<String>,
    pub FTNL_BASE_URL: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_TUNNEL_ID: Option<String>,
    pub FTNL_TIMEOUT_MS: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_STATE_DIR: Option<String>,
    pub FTNL_JSON: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FTNL_FLAGS_CONFIG: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub LOCALAPPDATA: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub XDG_STATE_HOME: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub FLAGS2ENV_COMMAND: Option<String>,
}
